### ISSUE TITLE
작동 여부

### ISSUE THREAD

**Issue by Hwan-seok** [Beomi/simple_bank_korea#3]
혹시 지금 작동하는 라이브러리인가요?

대략적으로 테스트 해보았을때 잘 되지 않아서... 혹시 실행 환경의 문제일까요?

**Comment by Beomi** [comment]
안녕하세요, 저번달까지만 해도 잘 작동했는데 안그래도 자동빌드 테스트에서 자꾸 실패해서 무엇이 문제인지 확인해 보니,
국민은행의 '빠른 조회' 서비스가 기존에 생년월일6자리를 사용했는데,
개인과 사업자 메뉴가 쪼깨지며 로그인 아이디를 입력하는 것으로 바뀌었네요.
제보 감사합니다.
오랫만에 코드 업데이트를 해야겠군요 :)

**Comment by Hwan-seok** [comment]
@Beomi 님 안녕하세요
먼저 정말 좋은 라이브러리 개발해주셔서 감사합니다 :-)

혹시 이 라이브러리가 요청하는 구간이 다음 사진 부분 맞을까요?
![image](https://user-images.githubusercontent.com/38072762/83613903-67617c00-a5bf-11ea-8912-f0bb2359175d.png)

해당 조회 서비스에서는 아직 생년월일을 입력하는것으로 보여져서 여쭤봅니다

또한,
국민은행 페이지가 떠있을때에는 `AhnLab Safe Transaction`이 기동되어 개발자도구 사용이 불가능하게 되었던데 혹시 어떻게 개발하신지 노하우를 알 수 있을까요?ㅠ

현재 프로덕션에서 `무통장 자동 입금 확인`을 개발하려고 하는데, 은행마다 여러 보안 때문에 빠른조회 서비스를 스크랩핑하기 쉽지 않네요..

많은 질문 죄송합니다

**Comment by Beomi** [comment]
넵 해당 페이지를 대신 긁어서 조회해주는 것이 맞습니다.
저도 다시 확인해보고 https://beomi.github.io/simple_bank_korea/ <- Demo Web page에서 테스트 해보니 정상적으로 잘 가져오는 것으로 보이는데요.
혹시 테스트 작업 환경이 Linux나 macOS가 아닌 windows이신가요?

+ 저는 macOS를 사용해서 AST가 뜨지 않습니다 :)

**Comment by Hwan-seok** [comment]
음.. 일단 제 테스트 환경은 `windows 10` 입니다

보내주신 계좌번호 `Demo Web Page`를 방금 시도해본 결과 `{"error": "Unknown Exception occured!"}`를 반환하는데 혹시 이유가 있을까요?

**Comment by Beomi** [comment]
그렇군요. 
Q1. 혹시 개인 계좌가 아니라 사업자 계좌인것은 아니죠? -- 혹시 국민은행에 요청을 보내는 것에 차이가 있을지 모르겠네요.
(제가 사업자 계좌가 없어 개인계좌로만 테스트를 진행하였습니다.)

Q2. 혹시 한번이 아닌 3-4번 시도시에도 동일하게 실패만 하고 에러가 지속적으로 발생하시나요?

**Comment by Hwan-seok** [comment]
1. 네, 개인 계좌입니다. 혹시 잘못된 정보를 입력했나 싶어서 동일한 정보로 https://obank.kbstar.com/quics?page=C025255&cc=b028364:b028702&QSL=F#loading 에 입력해보니 정상 처리되네요ㅠ
2. 네, 여러번 시도했지만 동일한 결과를 출력합니다

**Comment by tyc1048** [comment]
from simple_bank_korea.kb import get_transactions

# get_transactions returns list of dicts
# like this:
# [{'transaction_by': '', 'date': datetime.datetime(2017, 9, 11, 12, 39, 42), 'amount': 50, 'balance': 394}]

# example
transaction_list = get_transactions(
        bank_num='---',
        birthday='---',
        password='---',
        # days=30, # Optional, default is 30
        # PHANTOM_PATH='/Users/beomi/bin/phantomjs', # Optional, default is 'phantomjs' only.
        # LOG_PATH='/Users/beomi/phantom.log' # Optional, default is os.path.devnull (no log)
    )

for trs in transaction_list:
    print(trs['date'], trs['amount'], trs['transaction_by'])

테스트로 파이썬으로 바로 실행했을때 처리시간이 약 10초넘게 걸리는데 이러한 속도 부분은 서버영향인가요?

**Comment by Beomi** [comment]
안녕하세요, 

Linux와 macOS 관련해서 PhantomJS의 PATH를 설정하는 코드에 버그를 발견해 해당 부분을 수정하고
새로운 버전인 0.2.13을 릴리즈 & pypi에 업로드 해 두었습니다.
그리고 릴리즈 후 발견한 버그 (ㅠㅠ) 가 있어서 아마 오늘 내로 0.2.14를 업로드 할 것 같습니다. (PhantomJS Exec Permission error)
다만 윈도우의 경우는 코드 수정한 것이 없고,
기존의 test code 케이스를 성공적으로 통과해 사용상에는 문제가 없으셔야 정상입니다.
그리고 속도 테스트의 경우, PhantomJS를 다운받고 압축 푸는 부분을 제외하고 실제 코드 실행 시간은 평균 2-3초 이내로 보입니다. (맥북으로 테스트했습니다.)
혹시 매번 phantomJS를 다운받고있지는 않은지 확인을 해주실수 있으실까요?

**Comment by Beomi** [comment]
`pip install -U simple-bank-korea --index-url=https://pypi.org/pypi` 명령어로 새 버전을 설치후에도 안되시는지 확인 부탁드립니다 :)

**Comment by goldiutl** [comment]
Linux에서 실행하는데, phatomJS(path=,log=)이 부분에서 에러가 뜨네요..윈도우10에서는 잘 되던데 리눅스만 안되는 걸까요?

**Comment by goldiutl** [comment]
팬텀js가 안되서 크롬으로 했더니 되네요... 크롬과 크롬드라이버 깔아야하고, 둘 버전 맞춰져야지만 돌아가요... 리눅스이신분들은 참고하세요

패키지 안에 image_checker.py 코드를 수정해야합니다

팬텀js 대신 크롬드라이버를 불러줍니다

chrome_options = webdriver.ChromeOptions()
chrome_options.add_argument('--no-sandbox')
chrome_options.add_argument('--window-size=1920,1080')
chrome_options.add_argument('--headless')
chrome_options.add_argument('--disable-gpu')
driver = webdriver.Chrome('./chromedriver.exe', options=chrome_options)


하단에 crop부분이 있는데 다음과 같이 바꿔줍니다. 크롬이 캡쳐이미지를 가운데 정렬해서 맞추느라 삽질했네요

screenshot = Image.open(BytesIO(driver.get_screenshot_as_png()))
left = 875 - 17
top = 414 - 42
right = left + 205
bottom = top + 336
real = screenshot.crop((left, top, right, bottom))


+ 윈도우10에서도 돌아갑니다

**Comment by syriusta** [comment]
Session Expired! Get new touch keys
실행하면 위 메세지가 뜨는데 해결방법이 있나요?

**Comment by Beomi** [comment]
@syriusta 혹시 해당 이미지를 저장하는 임시 폴더가 생성이 되는지 + 사용하신 헤드리스 브라우저 버전이 무엇인지 알려주시면 확인이 가능할 듯 합니다.

**Comment by Beomi** [comment]
* 참고로 제 테스트 환경에서는 현재 패키지가 정상 작동합니다.(PhantomJS브라우저 사용)

**Comment by jongyoublee** [comment]
@Beomi 안녕하세요. 이번에 테스트용으로 맥에서 테스트 중입니다.

애플 M1 에어 사용중이며, 파이썬 3.9버전 사용중입니다. 
README에 있는 테스트코드를 실행시키면 syriusta 님처럼 같은 오류가 뜨면서 실행이 되지 않습니다.

sudo 권한을 주지 않으면 phantomjs path 부분에서 오류가 나며, sudo 권한을 주면 Session Expired가 됩니다

phantomjs 버전은 2.1.1 사용중이며, 실행 시 /tmp 폴더 내부에 아무내용도 생성되지 않습니다

*** 흑흑 해결했습니다 계좌번호가 잘못됐었네요...... 사업자계좌로도 정상적으로 잘 동작하네요 좋은 라이브러리 만들어주셔서 감사합니다

**Comment by Beomi** [comment]
잘 해결되셨다니 다행이네요.
이 이슈는 여기서 클로즈하겠습니다. 🙂

**Comment by syriusta** [comment]
저도 오늘 다시 작동해보니 정상작동 되는군요. 건드린것이 없는데.ㅜㅜ
그런데 주기적으로 실행해서 db에 저장하려고 하는데 pyinstaller로 exe파일 만들어서 실행을 하니 에러가 나는군요. 실행파일로는 안되는 건지요? 주기적으로 실행할 방법이 있어야 되는데.  누구 아시는분 도움좀 부탁드립니다.ㅜㅜ

**Comment by Beomi** [comment]
윈도우에서 주기적 실행은 파이썬 파일을 실행하는 스트립트: 예를들어 `python run.py` 라는 글을 담은 run_code.bat 파일을 만들어서,
해당 배치 파일을 윈도 스케쥴러에 등록하셔서 쓰시면 됩니다.

**Comment by syriusta** [comment]
파이썬 3.9버전이고 셀레니움 버전에 영향을 받는 거 같은데요 최신 셀레니움에서는 안되고 3.4버전으로 하니까 되는데 이게 정상인건지? 아니면 뭔가 있는건지.ㅜㅜ
셀레니움 4.3버전이면 module 'selenium.webdriver' has no attribute 'PhantomJS' 이 에러가 뜹니다.
